name: Scala CI (SMP)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Build Charm++
    - name: build-charm++
      run: |
        git clone https://github.com/UIUC-PPL/charm.git
        cd charm
        ./build charm++ netlrts-linux-x86_64 -g -j2 --with-production --enable-error-checking

    # Build Hypercomm
    - name: build-hypercomm
      run: |
        git submodule init
        git submodule update
        cd hypercomm
        cmake .
        make -j2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Run tests
      run: sbt test
      env:
        ERG_HOME: ${{ github.workspace }}
        CHARM_HOME: ${{ github.workspace }}/charm

    - uses: actions/upload-artifact@v2
      with:
        name: cpp-sources
        path: |
          ${{ github.workspace }}/*.cc
          ${{ github.workspace }}/ergc.jar
